### ISSUE TITLE
Error while loading entity prototype "Pony"

### ISSUE THREAD

**Issue by DonParpan** [suclearnub/my-little-factorio#1]
**Version:** 0.1.1

**Issue:** Error on load

**Steps to reproduce:**
1. Add mod
2. start game

**Additional information:** No thanks

**Log:** https://pastebin.com/Jh4WFCUL

**Comment by the-emerald** [comment]
Looks like the issue is with the fact that there's no sprite/animations that the "Pony" prototype can use. To-do in #2.

Will keep this issue open in case completing #2 does not solve the issue.

**Comment by the-emerald** [comment]
I am investigating using existing character model (one with hardhat) to test functionality in the rest of the mod, as art asset creation, even if just a placeholder, can take quite a bit of time.

**Comment by the-emerald** [comment]
Potential stopgap fix by using the existing character model done in f95364e - released as v0.1.2

Please check if it solves the issue.

**Comment by the-emerald** [comment]
Fixed in f95364e.
